# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Meiun Journey App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Meiun Journey App
  pod 'Firebase/Core'

  target 'Meiun Journey AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Meiun Journey AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
